dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: MQeqbRhPi/ab5UTFQid3iuIecrR1vaSczikRldSaVP2Lgh/StfG3KG1Kp2L88FHik3a/hWTqOU0exfQsnsWVdfRbaLzvMgj6Puk+PZivHbXqcIcCPk9AqMZfSYbMVwGyRcEJHMpiaH7AjdJwWYlHwSFwlVrrSjwcUCa/vUzw5bqvAGsOAd4bvLvNrnYX6ozCiC7fbtcSoE3SM395JHnlhq/xppa8qXBLxF52I8yTbaf6JxFWAPslx6UkiEjh11sTuDSieCExzTXBIaazWsFOHBSm4LRe2HyDto0XeeCCcsdPfRaJ2Iyj80aIdECARnx+2yOSBFlx2IjyYfa2owFF6e7C4CP+pfVKYqZKoo7VXo8+lekZHPmJB4luO2odPX1ENdLziwKPcf/wZ7OXnaek5lCyIwqAyTpHeIP6cCKH56tfpR1bAML6sh441jqWOvfrqh/wipFYOz0hxoWhffxwDx8NJ54l1OAoHu1/rXkqPzdqLnAvUig6eXpCTGj7LHSlqp27NFtc36Nk6+KZ8sPJp2hfgfbyW6SwcGigKvIFubJuIFEV1WzWTxCKSX/2dZVbL4exeRaoYEqk9Faq3PGpiGQ7kwqjMIVVJDwHHKC+sAENVCpVIn+z/bduYi4T9fYw6g+tGhcy5ymo/H5aOWvLy3OKGJ+lPwKrXVCFcuT4sxk=
