dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: b9NQmQXvuCIb49MHxclWfK2YXLIKJuqeQVEx54Mv/VNsZPBMBSaPOCL4DbGP9hHbn2Rjk9Cu3ohzE9ubkJY0tJ5uwVLJNOyq9elRQdHPBOxHJhu2gFR0txYIWPzIR2c9WgVVUTgBzCU31NnP5QdTP/acj/iIb+bz4YPAQC2/36WcLjSSB8F5RUsbVTK9nuv4F6AlNkee+AEpNyh0X2IzeURpY5A6ZXn5OUQLgj2wyzXnhmDyAnU6U3kIDfPdeEuhGDsAEc03QrsVKfjydFyrxFZUTu41sX2CxUGm/o1HoIDOS252G4sskk6/N/NI8muCQANt0I4AbKi+JkTIecdOBvUfsd4O1Ft1S79EDLJpHJTtctwl+Hqi474cIC28HD7oPE95cG4svULHe+ym6uIppLm2G+6vMmoT3WZdGcSswZBBq6M4f3nfHWVGLZfTwUrzIAwz+WCCP41dfclZhDzD87uht4lqXEwWBhE7bHRJ4sQwtj2wHELbMfvozVAH9v1Ph7eVRgpmpc5G9pg16w+bTYaXfYtrqza1KK6TBEqe8y1YiAKTV48u4YxcgWt54OBtEO9Se8G0yOIeOutd3BccoFIRP2wd+gvlJhmTiZfI4hS19Er2QbuxyURA4KSS3qbeXbRKhRqs198IfWJ6fh6Kq6RkEo+3yZKKc1IHzGO7Ruk=
