dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure:
"XNVrPxLElM0xjd/yUdru9quk0oBAfIIy9UFnbKxXXvPSzuzgkVCBuz34wTBcgjLHNGIb2gmGp3oD5V70YNrZuwxxa91ZMcGef+nlWBW1b1zdiJtVOSahvjjvsKtko7B1Dit4fTBd0sOzAx7xVoVmlb5HW1g3GhKx7bX/6sgSfFnzEkg0ywUzKzsPg2i4VlaPGCFx48zF4JLQ/HQe1u1o3KPJW42DaDtEMgVAZ0yH6wT5RN06/bj7z5OlDTgF/e7jNaZv65RDwILqNxZxFxlBd1F73+z7MbKt9gH2j8rBUon7A+uEMHMXGd+vaw6GZBeCZXfKpPtZqNpXESQ4UELayBVsEd0CySf1Ni5CA1DlmOS5cW38sp0oFLH5IdrBGJytrPj7LPH9mroOK8WDnko1HveM9Q7YugBdanpGt1bMQI7YEZNRPIlHErspYTA4TkQYVhUEHAVMYuTIHVGHfQ/O6Sjxwc9Jub5zjxYb+P/NTWzKFfUtPstwtFpL4AXrnV7d7zzmIBEA4OVZgAADCNoo52L3c8/vAvLYVMJ56MPDay2WelUALHSY1Kvv25i6Eo0d9yYVQsncYcjahh6nw/2NkIAYIOpJ+WpG2/vXao9tit+U3p37P/JFIqpcDh+vv0ycI01Swslw1YC8fj5uojI+PE7UQ4j7NinCVWFZlxtqVV8="
